import write_tool

def write_class( filepath, filename ):

    write_tool.write_top_file( filepath, filename, "cc" )
    fileclass = open(filepath+filename+".cc", 'a')
    fileclass.write( "%s::%s(){\n}\n\n" % (filename,filename) )
    fileclass.write( "%s::~%s(){\n}\n\n" % (filename,filename) )
    fileclass.close()

def write_header( filepath, filename ):

    write_tool.write_top_file( filepath, filename, "hh" )
    fileclass = open(filepath+filename+".hh", 'a')
    fileclass.write( "class %s\n{\n\n \tpublic:\n\n" % filename )
    fileclass.write( "\t\t//! Default Constructor\n" )
    fileclass.write( "\t\t%s();\n\n" % filename )
    fileclass.write( "\t\t//! Destructor\n" )
    fileclass.write( "\t\tvirtual ~%s();\n\n" % filename )
    fileclass.write( "\tpublic:\n\n" )
    fileclass.write( "\t\t// Write members here\n\n" )
    fileclass.write( "};\n\n" )
    fileclass.write( "#endif\n" )
    fileclass.close()

def write_rootclass( filepath, filename ):

    write_tool.write_top_file( filepath, filename, "cc" )
    fileclass = open(filepath+filename+".cc", 'a')
    write_tool.write_function_comment( fileclass, "Constructor" )
    fileclass.write( "%s::%s( TTree *tree )\n{\n" % (filename,filename) )
    fileclass.write( "\tmTree = tree;\n\n" )
    fileclass.write( "\tmTree->SetBranchAddress(\" \", , );\n\n" )
    fileclass.write( "\tmNevents = mTree->GetEntries();\n}\n\n" )
    write_tool.write_function_comment( fileclass, "Destructor" )
    fileclass.write( "%s::~%s()\n{\n\tdelete mTree->GetCurrentFile();\n}\n\n" % (filename,filename) )
    write_tool.write_function_comment( fileclass, "GetEntry" )
    fileclass.write( "Int_t %s::GetEntry( Long64_t entry )\n{\n" % filename )
    fileclass.write( "\treturn mTree->GetEntry( entry );\n}\n\n" )
    fileclass.write( "#endif")
    fileclass.close()

def write_rootheader( filepath, filename ):

    write_tool.write_top_file( filepath, filename, "hh" )
    fileclass = open(filepath+filename+".hh", 'a')
    fileclass.write( "class %s\n{\n\n \tpublic:\n\n" % filename )
    fileclass.write( "\t\t//! Default Constructor\n" )
    fileclass.write( "\t\t%s( TTree *tree );\n\n" % filename )
    fileclass.write( "\t\t//! Destructor\n" )
    fileclass.write( "\t\tvirtual ~%s();\n\n" % filename )
    fileclass.write( "\tpublic:\n\n" )
    fileclass.write( "\t\tTTree\t\t\t*mTree;\n" )
    fileclass.write( "\t\tLong64_t\t\tmNevents;\n\n" )
    fileclass.write( "\t\t// Declaration of leaf types\n\n" )
    fileclass.write( "\t\t// List of branches\n\n" )
    fileclass.write( "\t\tInt_t GetEntry( Long64_t entry );\n" )
    fileclass.write( "\t\tinline Long64_t GetEntries(){ return mNevents; };\n" )
    fileclass.write( "};\n\n" )
    fileclass.write( "#endif\n" )
    fileclass.close()

def write_histos( filepath, classname, filename ):

    write_tool.write_top_file( filepath, filename+"Histos", "cc" )
    filehistos = open( filepath+filename+"Histos.cc", "a" )
    filehistos.write("#include \"%s.hh\"\n\n" % classname )
    write_tool.write_mainfunction_comment( filehistos, "%sHistos" % filename )
    filehistos.write( "int %sHistos( TString dirin, TString dirout )\n{\n" % filename )
    filehistos.write( "\t// Create file to store histograms\n" )
    filehistos.write( "\tTFile *rootfile = new TFile( dirout+\"rootfiles/out_name.root\",\"RECREATE\");\n" )
    filehistos.write( "\tTH1F *htest = Utils1::bookTH1F( \"htest\", \"title;xtitle;ytitle;units\", nbins, xmin, xmax, true);\n\n" )
    filehistos.write( "\t// TChain to retrieve data\n" )
    filehistos.write( "\tTChain *c%s = new TChain(\"tree_name\");\n" % classname.lower() )
    filehistos.write( "\tc%s->Add(dirin+\"/file_name\");\n" % classname.lower() )
    filehistos.write( "\t%s *%s = new %s( c%s );\n" % (classname, classname.lower(), classname, classname.lower()) )
    filehistos.write( "\tLong64_t nevents = %s->GetEntries();\n\n" % classname.lower() )
    filehistos.write( "\t// Loop\n" )
    filehistos.write( "\tfor ( Int_t index = 0; index < nevents; index++)\n\t{\n" )
    filehistos.write( "\t\t%s->GetEntry(index);\n\n\t}\n\n" % classname.lower() )
    filehistos.write( "\trootfile->Write();\n")
    filehistos.write( "\trootfile->Close();\n\n")
    filehistos.write( "\treturn 0;\n\n}\n\n")
    filehistos.close()
    write_tool.write_help( filepath, filename+"Histos" )
    write_tool.write_main( filepath, filename+"Histos" )

def write_plots( filepath, classname, filename ):

    write_tool.write_top_file( filepath, filename+"Plots", "cc" )
    filehistos = open( filepath+filename+"Plots.cc", "a" )
    write_tool.write_mainfunction_comment( filehistos, "%sPlots" % filename )
    filehistos.write( "int %sPlots( TString dirin, TString dirout )\n{\n" % filename )
    filehistos.write( "\t// Create file to store histograms\n" )
    filehistos.write( "\tTFile *rootfile = new TFile( dirin+\"rootfiles/out_name.root\");\n" )
    filehistos.write( "\tTH1F *htest = Utils1::getTH1F( rootfile, \"htest\");\n\n" )
    filehistos.write( "\tTCanvas *c1 = NULL;\n" );
    filehistos.write( "\tc1 = Plot1::getCanvas(\"c1\",\"c1\");\n" )
    filehistos.write( "\thtest->Draw();\n" );
    filehistos.write( "\tUtils1::MyPrint(c1, dirout, \"Basic\", \"example\");\n" )
    filehistos.write( "\treturn 0;\n\n}\n\n" )
    filehistos.close()
    write_tool.write_help( filepath, filename+"Plots" )
    write_tool.write_main( filepath, filename+"Plots" )

def write_makefile( path, dirname, classname  ):

    filem = open( path+"/"+dirname+"/Makefile", "w" )
    filem.write("all:\n")
    filem.write("\tmake -C src\n")
    filem.write("\tmake -C make_histos\n")
    filem.write("\tmake -C make_plots\n\n")
    filem.write("clean:\n")
    filem.write("\tmake -C src clean\n")
    filem.write("\tmake -C make_histos clean\n")
    filem.write("\tmake -C make_plots clean\n")
    filem.close()

    filesrcm = open( path+"/"+dirname+"/src/Makefile", "w" )
    filesrcm.write( "CXX = g++\n" )
    filesrcm.write( "CXXFLAGS = -c -g -Wall -fPIC `root-config --cflags`\n")
    filesrcm.write( "ROOTLDFLAGS =  `root-config --glibs`\n" )
    filesrcm.write( "INCLUDE += -I$(JOYROOTROOT)/include -I$(%sROOT)/include\n" % dirname.upper() )
    filesrcm.write( "LDLIBS += -L$(JOYROOTROOT)/lib -lJOYROOT\n\n")
    filesrcm.write( "OBJS = %s.o\n" % classname )
    filesrcm.write( "all: $(OBJS)\n\n" )
    filesrcm.write( "%.o: %.cc\n" )
    filesrcm.write( "\t $(CXX) $(CXXFLAGS) $(INCLUDE) $< -o $@\n\n")
    filesrcm.write( "clean:\n\t rm -f $(OBJS)" )
    filesrcm.close()

    filehism = open( path+"/"+dirname+"/make_histos/Makefile", "w" )
    filehism.write( "CXX = g++\n" )
    filehism.write( "CXXFLAGS = -c -g -Wall -fPIC `root-config --cflags`\n")
    filehism.write( "ROOTLDFLAGS =  `root-config --glibs`\n" )
    filehism.write( "INCLUDE += -I$(JOYROOTROOT)/include -I$(%sROOT)/include\n" % dirname.upper() )
    filehism.write( "LDLIBS += -L$(JOYROOTROOT)/lib -lJOYROOT\n\n")
    filehism.write( "OBJS = $(%sROOT)/src/%s.o\n" % (dirname.upper(),classname) )
    filehism.write( "TARGETS = BasicHistos.o\n" )
    filehism.write( "BINARIES = $(TARGETS:.o=)\n\n")
    filehism.write( "all: $(TARGETS) $(BINARIES)\n\n" )
    filehism.write( "%: %.o\n" )
    filehism.write( "\t$(CXX) $(ROOTLDFLAGS) $(INCLUDE) $(LDLIBS) $(OBJS) $< -o $@\n\n")
    filehism.write( "%.o: %.cc\n" )
    filehism.write( "\t $(CXX) $(CXXFLAGS) $(INCLUDE) $< -o $@\n\n")
    filehism.write( "clean:\n\t rm -f $(BINARIES) $(TARGETS)" )
    filehism.close()

    fileplom = open( path+"/"+dirname+"/make_plots/Makefile", "w" )
    fileplom.write( "CXX = g++\n" )
    fileplom.write( "CXXFLAGS = -c -g -Wall -fPIC `root-config --cflags`\n")
    fileplom.write( "ROOTLDFLAGS =  `root-config --glibs`\n" )
    fileplom.write( "INCLUDE += -I$(JOYROOTROOT)/include -I$(%sROOT)/include\n" % dirname.upper() )
    fileplom.write( "LDLIBS += -L$(JOYROOTROOT)/lib -lJOYROOT\n\n")
    fileplom.write( "OBJS = $(%sROOT)/src/%s.o\n" % (dirname.upper(),classname) )
    fileplom.write( "TARGETS = BasicPlots.o\n" )
    fileplom.write( "BINARIES = $(TARGETS:.o=)\n\n")
    fileplom.write( "all: $(TARGETS) $(BINARIES)\n\n" )
    fileplom.write( "%: %.o\n" )
    fileplom.write( "\t$(CXX) $(ROOTLDFLAGS) $(INCLUDE) $(LDLIBS) $(OBJS) $< -o $@\n\n")
    fileplom.write( "%.o: %.cc\n" )
    fileplom.write( "\t $(CXX) $(CXXFLAGS) $(INCLUDE) $< -o $@\n\n")
    fileplom.write( "clean:\n\t rm -f $(BINARIES) $(TARGETS)" )
    fileplom.close()


def write_makefile2( path, dirname ):

    filem = open( path+"/"+dirname+"/Makefile", "w" )
    filem.write("all:\n")
    filem.write("\tmake -C make_plots\n\n")
    filem.write("clean:\n")
    filem.write("\tmake -C make_plots clean\n")
    filem.close()

    fileplom = open( path+"/"+dirname+"/make_plots/Makefile", "w" )
    fileplom.write( "CXX = g++\n" )
    fileplom.write( "CXXFLAGS = -c -g -Wall -fPIC `root-config --cflags`\n")
    fileplom.write( "ROOTLDFLAGS =  `root-config --glibs`\n" )
    fileplom.write( "INCLUDE += -I$(JOYROOTROOT)/include -I$(%sROOT)/include\n" % dirname.upper() )
    fileplom.write( "LDLIBS += -L$(JOYROOTROOT)/lib -lJOYROOT\n\n")
    fileplom.write( "TARGETS = BasicPlots.o\n" )
    fileplom.write( "BINARIES = $(TARGETS:.o=)\n\n")
    fileplom.write( "all: $(TARGETS) $(BINARIES)\n\n" )
    fileplom.write( "%: %.o\n" )
    fileplom.write( "\t$(CXX) $(ROOTLDFLAGS) $(INCLUDE) $(LDLIBS) $< -o $@\n\n")
    fileplom.write( "%.o: %.cc\n" )
    fileplom.write( "\t $(CXX) $(CXXFLAGS) $(INCLUDE) $< -o $@\n\n")
    fileplom.write( "clean:\n\t rm -f $(BINARIES) $(TARGETS)" )
    fileplom.close()

def write_setup( joypath, path, dirname ):
    fileset = open( path+"/"+dirname+"/setup.sh", "w" )
    fileset.write( "#!/bin/bash\n\n" )
    fileset.write( "source %s/setup.sh\n\n" % joypath )
    fileset.write( "export %sROOT=%s/%s" % (dirname.upper(), path, dirname) )
    fileset.close()

